name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-custom
      - v[0-9]+.[0-9]+.[0-9]+-custom-r[0-9]+

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            rust-target: x86_64-unknown-linux-gnu
          - os: macos-12
            rust-target: x86_64-apple-darwin
          - os: macos-12
            rust-target: aarch64-apple-darwin
    env:
      macosx_sdk: macosx12.3

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set RUST_TARGET
      run: echo 'RUST_TARGET=${{ matrix.rust-target }}' >> $GITHUB_ENV

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.rust-target }}
        default: true
        profile: minimal

    - name: Setup dependencies for Linux
      if: matrix.os == 'ubuntu-22.04'
      run: sudo apt-get -y -qq install libssl-dev libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

    - name: Set environment variables for Apple Silicon
      if: matrix.rust-target == 'aarch64-apple-darwin'
      run: |
        export SDKROOT=$(xcrun -sdk ${{ env.macosx_sdk }} --show-sdk-path)
        [[ -n $SDKROOT ]] && echo "SDKROOT=$SDKROOT" >> $GITHUB_ENV
        export MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk ${{ env.macosx_sdk }} --show-sdk-platform-version)
        [[ -n $MACOSX_DEPLOYMENT_TARGET ]] && echo "MACOSX_DEPLOYMENT_TARGET=$MACOSX_DEPLOYMENT_TARGET" >> $GITHUB_ENV

    - name: Build
      run: make

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: '*.tar.xz'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
